### ISSUE TITLE
启动时候 以--nostd 启动，偶尔出现 stdwriter 为空错误

### ISSUE THREAD

**Issue by zhiyunliu** [zhiyunliu/glue#7]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5c9354]

goroutine 1 [running]:
github.com/zhiyunliu/golibs/xlog.(*stdWriter).Close(0xc0000a97f0)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/golibs/xlog/stdout.writer.go:78 +0x14
github.com/zhiyunliu/golibs/xlog.(*StdoutAppender).Close.func1()
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/golibs/xlog/stdout.appender.go:51 +0x3a
sync.(*Once).doSlow(0x48f5d7, 0xc0000a9888)
        /usr/local/go117/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /usr/local/go117/src/sync/once.go:59
github.com/zhiyunliu/golibs/xlog.(*StdoutAppender).Close(0xcb28e0)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/golibs/xlog/stdout.appender.go:49 +0x45
github.com/zhiyunliu/golibs/xlog.(*logWriter).Detach(0xc00014c040, {0xdab714, 0x6})
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/golibs/xlog/appender.go:42 +0xa5
github.com/zhiyunliu/golibs/xlog.RemoveAppender(...)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/golibs/xlog/writer.go:35
github.com/zhiyunliu/glue/cli.(*ServiceApp).run(0xc000088630)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/glue/cli/service.run.go:18 +0x58
github.com/zhiyunliu/glue/cli.(*ServiceApp).Start(0xc000088630, {0xc000088630, 0xee34d8})
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/glue/cli/service.start.go:19 +0x119
github.com/kardianos/service.(*systemd).Run(0xc0004b7860)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/kardianos/service/service_systemd_linux.go:222 +0x37
github.com/zhiyunliu/glue/cli.doRun(0xc00030e160)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/glue/cli/cmd.run.go:30 +0x77
github.com/urfave/cli.HandleAction({0xc81300, 0xde4d08}, 0x3)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/urfave/cli/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xda8952, 0x3}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xdd8174, 0x6a}, {0x0, ...}, ...}, ...)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/urfave/cli/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc000172540, {0xc000100050, 0x5, 0x5})
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/urfave/cli/app.go:277 +0x705
github.com/zhiyunliu/glue/cli.(*App).Start(0xc0003c41b0)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/glue/cli/app.go:28 +0xfe
github.com/zhiyunliu/glue.(*MicroApp).Start(...)
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/vendor/github.com/zhiyunliu/glue/micro.app.go:31
main.main()
        /var/lib/gitlab-runner/builds/0365871b/0/microservice/payment/apiserver/main.go:18 +0x38

**Comment by zhiyunliu** [comment]
已处理，是因为在执行go p.handle 的时候， 对象的回收与异步任务冲突造成，将回收处理逻辑放入handle 内部解决。
